# Generated by Django 4.2.5 on 2024-07-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbuy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='address',
        ),
    ]
