# Generated by Django 4.2.5 on 2024-07-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('nearbuy_app', '0003_register_user_city_register_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.user'),
        ),
    ]
