# Generated by Django 4.2.5 on 2024-08-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('nearbuy_app', '0004_alter_register_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.user'),
        ),
    ]
