# Generated by Django 4.2.5 on 2024-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearbuy_app', '0005_alter_register_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100)),
                ('user_phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
