# Generated by Django 4.1.6 on 2024-09-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbuy_app', '0006_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
