# Generated by Django 4.2.5 on 2024-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegister',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=50)),
                ('point_of_contact', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('terms', models.TextField()),
            ],
        ),
    ]
