# Generated by Django 4.2.5 on 2024-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorregister',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
