# Generated by Django 4.2.5 on 2024-08-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor_app', '0003_delete_vendorregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=50)),
                ('point_of_contact', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('terms', models.TextField()),
                ('uname', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('cpassword', models.CharField(max_length=128)),
            ],
        ),
    ]
