# Generated by Django 4.2.5 on 2024-08-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_holder_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ifsc_code',
            field=models.CharField(default='', max_length=11),
        ),
    ]
