# Generated by Django 4.2.5 on 2024-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_vendor_account_holder_name_vendor_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
