# Generated by Django 4.2.5 on 2024-08-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0006_vendor_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='point_of_contact',
            field=models.IntegerField(default=0),
        ),
    ]
