# Generated by Django 4.1.6 on 2024-09-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0007_alter_vendor_point_of_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
