# Generated by Django 4.2.5 on 2024-07-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_add_fields',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
