# Generated by Django 4.2.5 on 2024-09-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='vouchercoupon',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='Dealers',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='VoucherCoupon',
        ),
    ]
