# Generated by Django 4.2.5 on 2024-09-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchercoupon',
            name='voucher',
        ),
    ]
