# Generated by Django 4.2.5 on 2024-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0003_remove_register_dealer_merchant_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_outlet_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_price', models.IntegerField(blank=True, max_length=8, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('item_img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
