# Generated by Django 4.1.6 on 2024-09-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0004_remove_vouchercoupon_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=50)),
                ('point_of_contact', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('account_holder_name', models.CharField(default='', max_length=255)),
                ('bank_name', models.CharField(default='', max_length=255)),
                ('branch', models.CharField(default='', max_length=255)),
                ('account_number', models.CharField(default='', max_length=20)),
                ('ifsc_code', models.CharField(default='', max_length=11)),
                ('terms', models.TextField()),
                ('uname', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('cpassword', models.CharField(max_length=128)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='dealers',
            name='business_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='merchant_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='merchant_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('spa', 'Spa'), ('saloon', 'Saloon')], default='hotel', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='outlet_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100)),
                ('user_phone_number', models.CharField(max_length=10, unique=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='deal_app.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='dealers',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deal_app.vendor'),
        ),
    ]
