# Generated by Django 4.2.5 on 2024-07-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0005_outlet_outletfields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdealer',
            old_name='drop_merchant_type',
            new_name='merchant_type',
        ),
    ]
