# Generated by Django 4.2.5 on 2024-08-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('deal_app', '0006_rename_drop_merchant_type_registerdealer_merchant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdealer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.dealer'),
        ),
    ]
