# Generated by Django 4.2.5 on 2024-08-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0011_alter_outlet_user_alter_outletfields_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletfields',
            name='outlet',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='deal_app.outlet'),
        ),
    ]
