# Generated by Django 4.2.5 on 2024-08-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0013_remove_outletfields_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletfields',
            name='description',
        ),
        migrations.RemoveField(
            model_name='outletfields',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='outletfields',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='outletfields',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='outletfields',
            name='user',
        ),
        migrations.AddField(
            model_name='outletfields',
            name='outlet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='deal_app.outlet'),
        ),
        migrations.AlterField(
            model_name='outletfields',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='outletfields',
            name='item_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
