# Generated by Django 4.2.5 on 2024-08-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0014_remove_outletfields_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='item_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='OutletFields',
        ),
    ]
