# Generated by Django 4.2.5 on 2024-08-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('deal_app', '0015_outlet_about_outlet_item_price_delete_outletfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.dealer'),
        ),
    ]
