# Generated by Django 4.2.5 on 2024-08-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('deal_app', '0017_alter_registerdealer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('spa', 'Spa'), ('saloon', 'Saloon')], max_length=30, null=True)),
                ('merchant_address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('item_img', models.ImageField(blank=True, upload_to='images/')),
                ('item_price', models.IntegerField(blank=True, default=0, null=True)),
                ('about', models.TextField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='registerdealer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Outlet',
        ),
        migrations.DeleteModel(
            name='RegisterDealer',
        ),
    ]
