# Generated by Django 4.2.5 on 2024-08-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0018_dealers_remove_registerdealer_user_delete_outlet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='merchant_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restuarent', 'Restuarent'), ('spa', 'Spa'), ('saloon', 'Saloon')], max_length=30, null=True),
        ),
    ]
