# Generated by Django 4.2.5 on 2024-08-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0019_alter_dealers_merchant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
