# Generated by Django 4.2.5 on 2024-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0020_alter_dealers_end_time_alter_dealers_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_price', models.IntegerField(blank=True, default=0, null=True)),
                ('voucher_about', models.TextField(blank=True, default='', null=True)),
                ('voucher_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dealers',
            old_name='description',
            new_name='outlet_description',
        ),
        migrations.RenameField(
            model_name='dealers',
            old_name='item_img',
            new_name='outlet_img',
        ),
        migrations.RenameField(
            model_name='dealers',
            old_name='item_name',
            new_name='outlet_name',
        ),
        migrations.RemoveField(
            model_name='dealers',
            name='about',
        ),
        migrations.RemoveField(
            model_name='dealers',
            name='item_price',
        ),
    ]
