# Generated by Django 4.2.5 on 2024-08-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0021_voucher_and_more'),
    ]

    operations = [
    ]
