# Generated by Django 4.2.5 on 2024-08-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0022_auto_20240821_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal_app.dealers'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_price',
            field=models.IntegerField(default=0),
        ),
    ]
