# Generated by Django 4.2.5 on 2024-08-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0024_voucher_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='business_owner_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dealers',
            name='contact_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
