# Generated by Django 4.2.5 on 2024-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0025_dealers_business_owner_name_dealers_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
